# -*- coding: utf-8 -*-
"""personal tasks manger

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNnmsM9RDRi5flZwH7vWLq2PoV6IyGNw
"""

import json
FILE_NAME = "my_routine.json"
def save_tasks(tasks):
    try:
         with open(FILE_NAME, "w") as file:
             json.dump(tasks, file, indent=4)

         print(f"Successfully saved{len(tasks)} tasks.")

    except Exception as e:
        print(f" An error occured:{e}")
def load_tasks():
    try:
         with open(FILE_NAME, "r")as file:
              return json.load(file)
    except FileNotFoundError:
        return[]

my_routine = [
    "wakup early ",
    "freshn up",
    "gym",
    "breakfast",
    "coding"
    ]



save_tasks(my_routine)

loaded_tasks = load_tasks()

print(loaded_tasks)

print("1. view tasks")
print("2. add tasks")
print("3. Delete tasks")
print("4. Exit")

choice = int(input("enter your choice:"))

for i, tasks in enumerate(loaded_tasks, start=1):
    print(f"{i}. {tasks}")

if choice == 1:
     if len(loaded_tasks) == 0:
         print("No tasks found.")
     else:
         for i, task in enumerate(loaded_tasks, start=1):
             print(f"{i}. {task}")

elif choice == 2:
    new_tasks = input("enter new tasks:")
    loaded_tasks.append(new_tasks)
    with open(FILE_NAME, "w") as file:
        json.dump(loaded_tasks, file)
    print("tasks added successfully!")

elif choice == 3:
     if len(loaded_tasks) == 0:
         print("no tasks to delete.")
     else:
          for i, task in enumerate(loaded_tasks, start=1):
              print(f"{i}. {task}")

     delete_tasks = int(input("enter tasks number to delete:"))
     if 1 <=  delete_tasks <= len(loaded_tasks):
          loaded_tasks.pop(delete_tasks-1)

          with open(FILE_NAME, "w") as file:
            json.dump(loaded_tasks, file)

          print("tasks deleted successfully!")
     else:
          print("invalid tasks number")

elif choice == 4:
    print("Thank You!")

else:
    print("Invalid Choice")

import os
print(os.getcwd())

import os
print(os.listdir())